### ISSUE TITLE
Campus Map

### ISSUE THREAD

**Issue by aneesh-neelam** [CollegeCODE/CreativeContent#2]
Hey, who has the campus map? The one that Senthil had asked us to put in our apps? 

Could you please send it to me? Email it to [neelam.aneesh@gmail.com](mailto:neelam.aneesh@gmail.com).

**Comment by kishore-narendran** [comment]
I think you should ask Senthil. He will know who made it and has the original file. 

-----Original Message-----

**Comment by biocross** [comment]
Here: 

https://github.com/CollegeCODE/VITacademics-Glass-iOS/blob/d42053742f672e1924bf26a70f8f975445fdd693/VITacademics-Glass/vitmap.jpg

**Comment by aneesh-neelam** [comment]
Campus map added, check repository. Took from iOS app's repository.
